### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by simoniman1** [Bluethefurry/EasyAdmin#10]
So ive been searching through this over and over and i cant for the life of me get why normal user get the ability to kick and ban and even get the menu open and also the premissions is all set to false yet it apears on the easy admin menu and the F2 button works to change to F10 but when i add it to the main server it changes back to F2 for some reason when my test server and my main server have the exact same code.

ban = false,
	kick = false,
	spectate = false,
	unban = false,
	teleport = false,

**Comment by Bluethefurry** [comment]
1) stop editing source code please
2) please read the wiki and
3) please use the latest version.
