### ISSUE TITLE
Game crashes when pressing f6

### ISSUE THREAD

**Issue by UdenRp** [Bluethefurry/EasyAdmin#101]
I installed everything correctly i suppose but when i press the butten it crashes eny help please

**Comment by Bluethefurry** [comment]
which EasyAdmin version are you using? also send your Citizenfx.log file please.

**Comment by UdenRp** [comment]
1 sec

**Comment by UdenRp** [comment]
Latest version

**Comment by UdenRp** [comment]
Master

**Comment by Bluethefurry** [comment]
try https://github.com/Bluethefurry/EasyAdmin/releases/tag/4.91 instead.

**Comment by UdenRp** [comment]
ok ima try i will let u know

**Comment by UdenRp** [comment]
Ok m8 it worked thanks my dude :D
