### ISSUE TITLE
How to add custom options?

### ISSUE THREAD

**Issue by Robijntjee** [Bluethefurry/EasyAdmin#112]
Hey, 

I want like a simple menu in EasyAdmin for chosing the weather & noclip (Just an ExecuteCommand?)
###### _im new to Development so idk how to add this in the menu, im stupid_ 😝

**Comment by Bartixxx32** [comment]
use vMenu

**Comment by Bluethefurry** [comment]
this isn't in the scope of what easyadmin can do for now, as mentioned by bartixx, there are a few alternative resources that could be used to fulfill these tasks
