### ISSUE TITLE
[Enhancement] Databases ( SQL / CouchDB )

### ISSUE THREAD

**Issue by CakeArmy** [Bluethefurry/EasyAdmin#12]
Hi, we have 3 servers and were wondering if there would be  an easy way to sync the banlists between the servers? Whether using CouchDB or mySQL it would be a feature we very much would appreciate. 

If you could tell me a good way to implement it, I would be okay to implement it for myself only, not requiring you to update your script.

**Comment by CakeArmy** [comment]
Nevermind, found a better solution. For those who want to do the same, I reccomend the mklink /H command. Here is an article that might help:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

And here is what I did:
1) Command Prompt (ADMIN)

2) mklink /H C:\Users\Administrator\Desktop\FTP\fivem_server
s\Server_2\resources\[categories]\[ADMIN]\EasyAdmin\banlist.txt C:\Users\Adminis
trator\Desktop\FTP\fivem_servers\Server_1\resources\[categories]\[ADMIN]\EasyAdm
in\banlist.txt

3) No matter which file I edit, they both sync together.

**Comment by CakeArmy** [comment]
I am pretty dumb. Although this works, EasyAdmin requires a restart before the change to the banlist takes effect. This means its not a viable option. Why doesnt it check the banlist on every player join from the file, rather than from the cache? (I have no clue how this works)

**Comment by Bluethefurry** [comment]
> EasyAdmin requires a restart before the change to the banlist takes effect

no, EasyAdmin should refresh the banlist every 5 minutes iirc

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/commit/4ba1303aae5dda64784a1b046c42eb98a710573e

**Comment by Bluethefurry** [comment]
this will work very similair to essentialmodes custom data implementation, you can make your own "custom data" resources if you want, i will only support the two most common mysql implementations.

**Comment by Bluethefurry** [comment]
:o https://github.com/Bluethefurry/EasyAdmin-MySQL
