### ISSUE TITLE
Not compatible with OneSync Infinity

### ISSUE THREAD

**Issue by rubbertoe98** [Bluethefurry/EasyAdmin#124]
WIth onesync infinity, it'll only show the players close to you in the userlist, as GetPlayerFromServerId will return nil for anyone not in your "zone".

**Comment by Bluethefurry** [comment]
as discussed on discord, changing the method we currently use would make the UI way slower than it currently is, i'd rather wait until fivem adds a real function to get all players.

**Comment by Poggicek** [comment]
It can easily be fixed without any performance hit. You just have to thing about all the solutions more.
Maybe stop thinking about syncing with the server everytime you open the menu

**Comment by cosminwindox** [comment]
i have the same problem, did u solved @rubbertoe98 ?

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/releases/tag/5.21
