### ISSUE TITLE
I cant open EasyAdmin menu.

### ISSUE THREAD

**Issue by MattyCZE95** [Bluethefurry/EasyAdmin#127]
As superadrmin, admin or moderator i cant open the EasyAdmin menu. I write to cofig as menu 344 (F11) but 0 error in console or F8

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/wiki/4.-Troubleshooting#my-permissions-dont-work-righti-cant-open-the-menu

**Comment by MattyCZE95** [comment]
i do it. but write me all false
