### ISSUE TITLE
Hear ingame voice during spectate

### ISSUE THREAD

**Issue by mejmej** [Bluethefurry/EasyAdmin#13]
Yo btf 👍 
I was wondering if it was possible to add the ability to hear ingame voice during the spectate? We admins often listens in on roleplay scenarios to help those who need training :)

Cheers

**Comment by Bluethefurry** [comment]
this is not possible due to the fact that your ped needs to be in the area to hear it, the game ignores where the camera is located.

**Comment by mejmej** [comment]
Are you not able to place the ped behind the spectated player as a invisible user? :)

**Comment by Bluethefurry** [comment]
that *could* work, but would not be very efficient nor useful

**Comment by mejmej** [comment]
I would say it is useful. Me as an administrator would like to spectate the roleplay some times so that I can either help the people be better at RP or just be a spectator to watch if there are any rules that are broken.

**Comment by Bluethefurry** [comment]
This seems like such a horribly specific issue i doubt it's worth looking into.

**Comment by Bluethefurry** [comment]
I have taken a look at it again, and without some *proper* rewriting, this is out of the scope, mainly because it barely has any proper use other than hearing voice chat.

**Comment by onno204** [comment]
I've created a little script for this which usses "NetworkOverrideReceiveRestrictions(GetPlayerFromServerId(Pid), state)"

**Comment by Bluethefurry** [comment]
I believe since we have mumble integration now this doesnt matter, although i didnt really test it I BELIEVE that i heard someone talk

**Comment by onno204** [comment]
Yeah. The problem is that if you want to hear everyone you need to loop trough the players. Check range. And update if they can here u. And update about every 10sec.

And we haven't got mumble. So I hope it works with that
