### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by XxPunanixX** [Bluethefurry/EasyAdmin#138]
I am using EasyAdmin for my server and vMenu, it's been working great until recently, I haven't touched anything within the resources coding but for some reason I cant give one of my admins admin permission ingame, I have doubled checked that I am using the right hex-id, I have tried using fivem license and he has tried with two different accounts.

**Comment by Bluethefurry** [comment]
unless you, or a resource on your server, specifically denies certain permissions there will be no issue, enable debugging, if the perms show that he isnt admin then theres something wrong in your configuration
