### ISSUE TITLE
Player order.

### ISSUE THREAD

**Issue by Dennis-NL** [Bluethefurry/EasyAdmin#141]
Players are no longer ordered in the player/cache playerlist.
This is very annoying when you have 80+ players.

Is there a reason why this got removed? and wil it get fixed in the future?

**Comment by Bluethefurry** [comment]
Currently its been removed due to a rushed fix for onesync bigmode as some code was modified, so the old sorting logic no longer worked, it's on the list to reimplement

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/pull/142
should re-add this, although unsure if it works as i have no means to test it currently

**Comment by Dennis-NL** [comment]
I can confirm that this works!
