### ISSUE TITLE
EasyAdmin broken

### ISSUE THREAD

**Issue by JuiceIQ** [Bluethefurry/EasyAdmin#143]
I cant talk to people while spectaing cannot refresh cached players and also the list of the playerlist is not from newest players

**Comment by JuiceIQ** [comment]
![image](https://user-images.githubusercontent.com/68517486/87884929-baf91f00-c9df-11ea-8185-21eff3de4b6c.png)

**Comment by Bluethefurry** [comment]
please try that again with proper punctiation, so your sentence can actually be read.
