### ISSUE TITLE
Not showing up when pressing custom key

### ISSUE THREAD

**Issue by rjneco** [Bluethefurry/EasyAdmin#144]
after some troubleshooting I have found my error to be replicable within my server. EA was not loading after switching from the F2 key. However, when I press the F2 first and then my designed key, it will open. On the debugging console it seems like F2 is the key which logs the permissions and only after pressing F2 i get the main menu to open.

**Comment by Gtalavero** [comment]
Same for me... Don't know why. I will take a seat there to get info

On question, what is the debugging console? It would be usefull for me. Thanks!

**Comment by Bluethefurry** [comment]
Make sure you use the latest *RELEASE*, not Master, also enable debugging ( see wiki ) and upload your server-side console output.

**Comment by AdventurePandah** [comment]
I have the same, the keybind change doesn't work. I'm using the latest release

**Comment by therealknight** [comment]
> I have the same, the keybind change doesn't work. I'm using the latest release

Read the comment above yours, I have no issues changing the key on the latest version

**Comment by AdventurePandah** [comment]
> > I have the same, the keybind change doesn't work. I'm using the latest release
> 
> Read the comment above yours, I have no issues changing the key on the latest version

You're using Coldfix 5.215?

**Comment by therealknight** [comment]
> > > I have the same, the keybind change doesn't work. I'm using the latest release
> > 
> > 
> > Read the comment above yours, I have no issues changing the key on the latest version
> 
> You're using Coldfix 5.215?

That is the latest version, yes.

**Comment by Bluethefurry** [comment]
i'd recommend joining the discord and throwing your server.cfg into the support-ea channel, that way the bot will check if everything is set up correctly, the custom key definetely works as long as you followed the wiki.

**Comment by rjneco** [comment]
Fixed by updating line 726 of admin_server.lua with your latest update

**Comment by Bluethefurry** [comment]
Like i said..
https://github.com/Bluethefurry/EasyAdmin/issues/144#issuecomment-674391819
