### ISSUE TITLE
Teleport and spectate !

### ISSUE THREAD

**Issue by Enric42** [Bluethefurry/EasyAdmin#146]
in the last fivem artefact , in the menu we don't have teleport and spectate

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/blob/master/admin_server.lua#L1036

**Comment by Enric42** [comment]
thx for help , i have always this problem ,although I have this line in my easy admin , 
what should I do ?

**Comment by Bluethefurry** [comment]
sigh, read the code, dont use onesync infinity.
