### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by FAXES** [Bluethefurry/EasyAdmin#16]
I get this in my console. The script works fine its just that...
```
Error running system event handling function for resource EasyAdmin: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: admin_server.lua:424: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        admin_server.lua:424: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
```

**Comment by Bluethefurry** [comment]
when does the error appear? it seems to be caused by the banlist.json failing to load.

**Comment by FAXES** [comment]
It constantly prints out. every couple minutes.

It also happens when a;
- Player connects
- Player Spawns
- x8 time when a player is kicked
- When a banned player re joins

Those are the times I found and just retested.

**Comment by FAXES** [comment]
It also seems to stop me from banning now after all that, worked before though.

**Comment by Bluethefurry** [comment]
uh, how does your banlist file look? maybe its a conversion error or so

**Comment by FAXES** [comment]
It came up a lot of time repeated in the console. Ban list file is 100% empty.

My version is  4.201.

**Comment by Bluethefurry** [comment]
100% empty or contains []?

**Comment by Bluethefurry** [comment]
editing ban times is planned, also, please delete your banlist.json and try again.

**Comment by FAXES** [comment]
Ok thanks heaps Ill give her a try.

**Comment by FAXES** [comment]
Ok deleting the ban list file worked.

Thanks for all the support.

**Comment by Bluethefurry** [comment]
👍 , no idea why it was empty in the first place though.
