### ISSUE TITLE
Fixing banlist issue

### ISSUE THREAD

**Issue by Ascaped** [Bluethefurry/EasyAdmin#18]
https://github.com/Bluethefurry/EasyAdmin/blob/41e6348a55860338bdd2d0067393b571328f45c9/admin_server.lua#L422

`AddEventHandler('playerConnecting', function(playerName, setKickReason)
		local numIds = GetPlayerIdentifiers(source)
		local content = LoadResourceFile(GetCurrentResourceName(), "banlist.json")
		testblacklist = json.decode(content)
		for bi,blacklisted in ipairs(testblacklist) do
			for i,theId in ipairs(numIds) do
				if blacklisted.identifier == theId then
					Citizen.Trace("user is banned")
					setKickReason(string.format( strings.bannedjoin, testblacklist[bi].reason, os.date('%d/%m/%Y 	%H:%M:%S', testblacklist[bi].expire )))
					print("Connection Refused, Blacklisted for "..testblacklist[bi].reason.."!\n")
					CancelEvent()
					return
				end
			end
		end
	end)`

**Comment by Bluethefurry** [comment]
if you want to fix an issue or propose a fix, use pull requests, not issues.
