### ISSUE TITLE
Adding more features 

### ISSUE THREAD

**Issue by FeaReDGlock** [Bluethefurry/EasyAdmin#21]
I was thinking of putting features that will just serve to administrate a server.

- Freeze Player
- Kill a player (Not sure but maybe not, just in case the freeze don"t work of something like that)
- Teleporting to a waypoint (Can be useful)
- Reload a ressource (Useful when you are modifying something and you don't want to reload the server, like blip on map)
- Noclip (Not sure) (Maybe to hide when you are spectating someone)
- Ban a player with his name even if he is not online (**DB Method** : You write his name, that will search in the database, his name and it goes ban his steamid)
**(Non DB method)**
Or maybe when you freeze a player his name is enter in a txt and if he leave while freezed, you have his name in the txt because its only when you unfreezed him the name disappear in the txt.
When you have banned him, add an option to clear the file.

And that's it, i don't know what you could add :)

**Comment by CruelAlpha** [comment]
Hey @Bluethefurry Possible / is there a function for logs? of admin commands? Thanks!

**Comment by CruelAlpha** [comment]
so it would send it via webhook? Thanks

**Comment by Bluethefurry** [comment]
> Hey @Bluethefurry Possible / is there a function for logs? of admin commands? Thanks!

Admin Actions are already logged by using the webhook functionality, i just created a [wiki page](https://github.com/Bluethefurry/EasyAdmin/wiki/6.-Monitoring-Actions) for it to better detail it.

**Comment by CruelAlpha** [comment]
Hey! Thanks, thats great, do spectate triggers get logged aswell?
Thanks!

**Comment by Bluethefurry** [comment]
> do spectate triggers get logged aswell

No they are not, only essential functions are logged ( kicks, bans, unbans )

**Comment by Bluethefurry** [comment]
Update on this:
❔  = is being worked on / delayed / planned
✅ = done
❌ = not happening

Kill/Slap Player: ❔  
Teleporting to a waypoint: ❌ 
Reload a ressource: ✅
Noclip: ❌ 
offline bans: ❔
