### ISSUE TITLE
Unban player not working

### ISSUE THREAD

**Issue by AdriaanBoshoff** [Bluethefurry/EasyAdmin#26]
I did the following.

1. Banned a friend to test the bans.
2. Refreshed the ban list.
3. reopened the menu.
4. Tried to unban but doesnt show.
5. Tried to unban via commands even tho it says Done it didnt to a thing.

The only way I could unban him was to remove him from the banlist file and restart the server

**Comment by Bluethefurry** [comment]
can you give me your sample banlist file? I'll take a look.

**Comment by CakeArmy** [comment]
I am also having this issue. I have to unban people manually and then wait to restart the server. Running     "version":"4.3",
(found in version file) 

This is my banlist: https://hastebin.com/kuxidujotu.json

**Comment by AdriaanBoshoff** [comment]
Sorry for the late reply. The bans file is the same as @CakeArmy but with different people ofcourse. The bans just doesn't show up on the menu.

**Comment by Bluethefurry** [comment]
i could never replicate this issue, sorry.

**Comment by Bluethefurry** [comment]
actually, i can replicate this, odd.

**Comment by Bluethefurry** [comment]
should be fixed in https://github.com/Bluethefurry/EasyAdmin/commit/e14c7196b0a0dcf65f91fac764ae4191c763e494
