### ISSUE TITLE
No longer can access the menu

### ISSUE THREAD

**Issue by Halotacos** [Bluethefurry/EasyAdmin#27]
Hi,  the server I work for loves this script (Ps it's amazing) But recently one of our admins can no longer access the menu. We have tried fixing it but we have no idea what is going on

**Comment by Bluethefurry** [comment]
did their identifier change? ( different steam account, different RSC account, etc ), you may have to update their identifier if that is the case.

**Comment by Halotacos** [comment]
No they have not. All of a sudden it just stopped opening for them.

**Comment by Bluethefurry** [comment]
for them.. JUST for them? Did you change permissions or something, my menu cant just stop working for one person only.

**Comment by Halotacos** [comment]
No, we have not. It is really weird because the owner can still access it. The one and only admin can not. We have truly no idea what is happening

**Comment by Bluethefurry** [comment]
then that is very likely that you just misconfigured it. If it works for one person, it should work for all of them

**Comment by Halotacos** [comment]
But, It was working before then all of a sudden it stopped working

**Comment by Bluethefurry** [comment]
EasyAdmin doesnt "just" stop working for specific users, either it ceases function completely and throws errors, or the user made a mistake.

**Comment by Bluethefurry** [comment]
Hey just checking in, has this issue been resolved or is the menu still broken?
