### ISSUE TITLE
4K Menu issue

### ISSUE THREAD

**Issue by onno204** [Bluethefurry/EasyAdmin#33]
For some people in my staff team the menu is f*cked up with 4K,

https://cdn.discordapp.com/attachments/373157409474084866/453290662977339402/unknown.png
https://cdn.discordapp.com/attachments/373157409474084866/453291700174061568/unknown.png

Is there any fix for this?

**Comment by Bluethefurry** [comment]
Did you try an unmodified version of EasyAdmin? Your version seems modified.

**Comment by onno204** [comment]
I have indeed created a heavily modified version of EasyAdmin.
I will try that asap when a staff with 4K comes online.

**Comment by Bluethefurry** [comment]
Hey, did you test an unmodified version yet?

**Comment by onno204** [comment]
It seems that a NativeUI update fixed it.
Sorry for not reporting back to you!
