### ISSUE TITLE
big problem xD

### ISSUE THREAD

**Issue by MAX3D11** [Bluethefurry/EasyAdmin#35]
hi 

i have anticheese-anticheat that use EasyAdmin to ban and somthing

the problem anticheese-anticheat  ban the Admin -___- how can i unban me to login without stop easyadmin to login 

i hope you understand me my english too bad

**Comment by SaltyGrandpa** [comment]
Modify the banlist.json file and remove yourself from it. The default file is just two brackets ( [] ), which is an empty JSON file.

To prevent this from happening again, whitelist yourself on anticheese-anticheat, as explained in the readme, using `add_ace group.admin anticheese.bypass allow`
