### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by vilhelm8** [Bluethefurry/EasyAdmin#37]
I have put all the set ea stuff in my server.cfg folder and i have NativeUI installed, i have also added: start EasyAdmin and start NativeUI into my server.cfg but when i load into the server and hit F2 it won't open. Please help me.

**Comment by REDRUM216** [comment]
Did you ever find a fix?

**Comment by REDRUM216** [comment]
"you need your steam64 id from any id finder, lets take mine for example, that would be 76561198049466851, now you want to convert that to hex, that makes it 1100001055119E3, then you put steam: infront so it’s steam:1100001055119E3, and thats how you put it in there!"

**Comment by Bluethefurry** [comment]
errors? logs? anything?

no logs, no help.
