### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by iFusionFr** [Bluethefurry/EasyAdmin#39]
Display problem when opening the menu.

I tried, but did not change anything:
Clear the server cache
Clear the client cache
Several reboot
Seconde Upload EasyAdmin

![20180715014305_1](https://user-images.githubusercontent.com/31099360/42729233-03f0eb32-87d1-11e8-9a0f-5c8ca7850966.jpg)

**Comment by iFusionFr** [comment]
It's set, but it's a shame that you have to restart your game for the menu position to take place.

**Comment by Bluethefurry** [comment]
Yup, but thats nothing i can fix, its due to the way "pools" in NativeUILua work.
