### ISSUE TITLE
Can't set a date?

### ISSUE THREAD

**Issue by Chojnackii** [Bluethefurry/EasyAdmin#41]
If i ban someone, it shows in chat 31/03/2013(someting like that). Anyone have a same issue? If someone resolve , write me. And sorry for my bad english.

**Comment by Chojnackii** [comment]
And If I ban for 1 day its ban permanetly

**Comment by Bluethefurry** [comment]
what is your server time set to? make sure its actually correct.

**Comment by Bluethefurry** [comment]
just tried to reproduce this, banning me for 1 minute unbanned me after a banlist refresh, working as intended

**Comment by Chojnackii** [comment]
Let  me know how to do this

**Comment by Bluethefurry** [comment]
depending on what your server is, you can check if the server time is correct by using the "time" or "date" command, google is your friend, but this is not an EasyAdmin issue

**Comment by Chojnackii** [comment]
I'll will  check this. I have  server on ZapHosting.

**Comment by Chojnackii** [comment]
There is no Command  like "date" , and  command "time" changing only time on  game

**Comment by Chojnackii** [comment]
In  The evening  i gonna search  for date change.

**Comment by Bluethefurry** [comment]
if it's a ZAP Server, i recommend either looking if you installed EasyAdmin wrong or contacting the ZAP Support regarding it as i can not replicate your issue
