### ISSUE TITLE
Investigate Memory Leak

### ISSUE THREAD

**Issue by Bluethefurry** [Bluethefurry/EasyAdmin#42]
also see https://github.com/FrazzIe/NativeUILua/issues/9#issuecomment-412851870

There is still a memory leak when creating the menu, not sure what causes it at this time

**Comment by Bluethefurry** [comment]
apparently 
https://github.com/FrazzIe/NativeUILua/pull/11
might work better than what is currently being used, if PR gets merged i will push an update that SHOULD fix the leak.

**Comment by Bluethefurry** [comment]
seems 4.45x solved this issue.

**Comment by TheSpartaPT** [comment]
you left a call to a function that doesn't exist named `collectgarbage()` on gui_c.lua ;)

**Comment by Bluethefurry** [comment]
collectgarbage() does exist and does work

**Comment by TheSpartaPT** [comment]
oh ok didn't think about it being a lua function, i'm at work and i saw that and thought to myself "well it isn't declared anywhere and it ain't a fivem native so yeah he must have had it declared before when testing and forgot to delete it", sorry xD
