### ISSUE TITLE
not working after the last update (yesterday)

### ISSUE THREAD

**Issue by whitewolftbc** [Bluethefurry/EasyAdmin#49]
Hi
I started my server and saw that update is available... 
downloaded it,deleted the old version and installed the new one,cleared cache and started server..
but when i press the menu key nothing happens ?!?
there are no errors in console

**Comment by Bluethefurry** [comment]
no errors, no support, i test every version for its reliability, did you download EasyAdmin AND NativeUILua, e.g. the pack from the "releases" section? otherwise it may not work correctly.

**Comment by Dragese** [comment]
I think, he doesn't change the buttom of menu.

**Comment by Dragese** [comment]
I was wrang, the same issuse.

**Comment by Bluethefurry** [comment]
Well, if you aren't getting any errors then i cant help you, there MUST be an error, otherwise it's user error.

**Comment by whitewolftbc** [comment]
there wasnt any error...
i just added some numbers to admin_server.lua/admins {} then when restarted it was saying error in admin_server.lua...
then i reversed it to default and its working..thats strange

**Comment by Bluethefurry** [comment]
it's almost like the notes of "dont touch shit" in the script files are there for a reason!!!
