### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by whitewolftbc** [Bluethefurry/EasyAdmin#53]
Hello
I used the EasyAdmin before and it was working..i installed it yesterday..
readed the wiki and putted all the needed stuff to server.cfg.
added myself to server.cfg admins
changed the button in server.cfg to be F5
also i downloaded the last version of NativeUI by frazzle
there is no errors but when i click the menu button nothing happens

server.cfg:
```
start NativeUI
start EasyAdmin

set ea_LanguageName "en"
set ea_MenuButton "116"
set ea_alwaysShowButtons "false"
set ea_moderationNotification "false"
set ea_custombanlist "false"

add_principal identifier.ip:[ip here] group.superadmin
add_principal identifier.steam:[steamid here] group.superadmin
add_ace group.superadmin easyadmin allow
```

If someone could provide some help would be greatly appreciated

Best regards

**Comment by whitewolftbc** [comment]
P.S: When i try to /kick id reason - it works and kicks me.. but when i want to open the menu...nothing happens...reinstalled NativeUI by frazzle - still the same

**Comment by Bluethefurry** [comment]
Getting any errors in client/server logs?

**Comment by whitewolftbc** [comment]
no..
seems like nativeui problem..commands like /kick /ban etc is working but when i press the button for the menu it doesnt appear..tried a couple versions...none of them seems to work

**Comment by Bluethefurry** [comment]
tried the latest? works fine here and for everybody else that uses the NativeUI+EasyAdmin pack.
