### ISSUE TITLE
Expired bans don't automatically remove themselves?

### ISSUE THREAD

**Issue by Xseba360** [Bluethefurry/EasyAdmin#54]
I've been facing a problem since I've started using EasyAdmin where bans don't correctly expire. After a ban has expired a person cannot join.

**Comment by Bluethefurry** [comment]
banlist takes ~5 minutes to refresh, are you using the MySQL Module or just the json file?

**Comment by Xseba360** [comment]
MySQL Module, happened back when i was using just the JSON file as well...

**Comment by Bluethefurry** [comment]
if you can provide with a consistent repo that works across all easyadmin installations, please do so, i can't replicate it myself.

**Comment by Bluethefurry** [comment]
closing this since author did not respond.
