### ISSUE TITLE
getting console errors

### ISSUE THREAD

**Issue by whitewolftbc** [Bluethefurry/EasyAdmin#56]
Hello,
so im getting the following error in console when i try to start EasyAdmin.
I installed the last version of EasyAdmin + the last version of NativeUI by frazzle and cleared cache
i didnt changed nothing to the scripts

`restart EasyAdmin[6G[Jrestart EasyAdmin[23G 
Stopping resource EasyAdmin 
Started resource EasyAdmin 
Error resuming coroutine: citizen:/scripting/lua/json.lua:397: bad argument #1 to 'strfind' (string expected, got nil) 
stack traceback: 
[C]: in function 'string.find' 
citizen:/scripting/lua/json.lua:397: in upvalue 'scanwhite' 
citizen:/scripting/lua/json.lua:553: in function <citizen:/scripting/lua/json.lua:551> 
(...tail calls...) 
admin_server.lua:467: in function 'updateBlacklist' 
admin_server.lua:586: in function 'loopUpdateBlacklist' 
admin_server.lua:596: in function <admin_server.lua:21> `

**Comment by Bluethefurry** [comment]
how does your banlist file look? does it exist? what is the content?

**Comment by Bluethefurry** [comment]
closing this since author did not respond.
