### ISSUE TITLE
Admins not loading

### ISSUE THREAD

**Issue by Bartixxx32** [Bluethefurry/EasyAdmin#58]
I have a bug idk what happend but if i add admin by addadmin command its works adding to admins.txt but after few restarts my admins cant open EasyAdmin i need add it agin and restart script it works for next restart too but in admins.txt it making double lines ( all looks good in this file ) I will just add if Menu not working sometimes a few restarts of fivem can help and they can use the menu i dont know whats happened

**Comment by Bluethefurry** [comment]
the admins.txt file has been obsolete for a very long time now, please use ACE instead ( https://github.com/Bluethefurry/EasyAdmin/wiki/2.-Configuring-Permissions )
