### ISSUE TITLE
Everyone has admin

### ISSUE THREAD

**Issue by fbagjug** [Bluethefurry/EasyAdmin#6]
Hello, I seemed to have run into a problem. I was on my server and a guy said that when he clicks F2 a ban menu comes up. I have tried changing the button from F2 to F9 but the menu still shows as F2. Everyone can kick and ban anyone from the server and im wondering why.

**Comment by Firecul** [comment]
If you changed F2 to F9 I assume you cleared the cached version on the server (I do that a lot while experimenting on menus) and restarted the server?
Not sure about the admin problem yet, I'll have to look through the code.

**Comment by fbagjug** [comment]
I just restarted the server because i found that deleting the cache can break the server sometimes

**Comment by Firecul** [comment]
Did you get an error with the session manager? If so When you delete the cache, restart the server, shut it down again and then when you bring it back up it'll work fine. (I now just delete the specific files/folders to avoid doing this but it only takes 5 seconds so not a big deal)

**Comment by Bluethefurry** [comment]
1) are you running es_admin
2) did you change the key via convars or via modifying code? make sure you set the convars before starting EasyAdmin ( although i doubt that changes anything )

**Comment by mejmej** [comment]
Hello. I have the same problem so I had to disable the script. 
I've only used convars for settings. Also it disables the ability to spectate a player via chat which I could before.
I'm running es_admin yes.

**Comment by Bluethefurry** [comment]
https://forum.fivem.net/t/release-easyadmin-its-as-easy-as-it-gets/42245/584?u=bluethefurry
