### ISSUE TITLE
Hide player id

### ISSUE THREAD

**Issue by kevintransp** [Bluethefurry/EasyAdmin#66]
Nice admin menu. After installing EasyAdmin my players see the ID's again above the heads. Before it where so that only admins see the ID's true installing https://forum.fivem.net/t/release-id-only-for-admin/73764/36
Is there something in your resource that make it so that the id numbers apairs again.

Thanks for reading.

**Comment by Bluethefurry** [comment]
no there is not, this is not related to easyadmin at all.
