### ISSUE TITLE
Stop people from kicking/banning people in defined groups

### ISSUE THREAD

**Issue by dennythepilgrim** [Bluethefurry/EasyAdmin#67]
Perhaps a way so that someone in group.moderator cannot kick someone in group.moderator or group.admin. Or a way to define groups that cannot be kicked or banned, like how vMenu has it set up.

**Comment by Bluethefurry** [comment]
this is definetely something that could be useful, maybe an "unkickable" permission? I'll add it for 4.6

**Comment by Bluethefurry** [comment]
https://github.com/Bluethefurry/EasyAdmin/commit/6cbacdcd47ccbde39c2eb1b1c4440f0ac67bf545
