### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by ralvarez710** [Bluethefurry/EasyAdmin#69]
This is my server config file I cannot get easy admin to recognize me as an admin.

I went through the Wiki to try and figure out the issue but I am still not seeing results.

**Comment by Bluethefurry** [comment]
Hm, that should work, are you getting any errors in the Server or Client Logs?

**Comment by ralvarez710** [comment]
This is what I get when I start my server. 

[serverlog.txt](https://github.com/Bluethefurry/EasyAdmin/files/2807593/serverlog.txt)

**Comment by ralvarez710** [comment]
@Bluethefurry I cant pull up easy admin I cant do anything with it.
almost like it doesn't exist. I have the keybinding set to f6 and it wont show.

**Comment by Bluethefurry** [comment]
Hm, seems to work fine too, can you please try replacing this:
https://github.com/Bluethefurry/EasyAdmin/blob/master/admin_client.lua#L25
with this function:

```
AddEventHandler('EasyAdmin:adminresponse', function(response,permission)
	permissions[response] = permission
	if permission == true then
		isAdmin = true
		Citizen.Trace("Player has EasyAdmin Access")
	end
end)
```

and check if that message gets printed in your F8 Logs?

**Comment by ralvarez710** [comment]
@Bluethefurry It does not get printed at all.

**Comment by ralvarez710** [comment]
Blue what is the best way to set the keybinding to something like perhaps F6?

**Comment by Bluethefurry** [comment]
If that message doesn't get printed then that means you don't have the permissions configured correctly, also, read the wiki.

**Comment by Bluethefurry** [comment]
closed due to inactivity.
