### ISSUE TITLE
Preset 3 day ban expire is actually only 2 days

### ISSUE THREAD

**Issue by blockba5her** [Bluethefurry/EasyAdmin#70]
The ban expire for 3 days only actually bans for 2 days. I checked and it's a *2 multiple of the 1 day. Also when you ban someone it displays the expire as 2 days from the time.

**Comment by Bluethefurry** [comment]
Fixed in https://github.com/Bluethefurry/EasyAdmin/commit/6a16e46a36ae191dada4546010dd79f8a69a7887

Thanks for the Report!
