### ISSUE TITLE
cant add someone as admin.

### ISSUE THREAD

**Issue by NisseA** [Bluethefurry/EasyAdmin#72]
Ive added myself as admin in system.cfg (SteamID) but nothing. 
Used RCON (addadmin ID) and it says that im an admin but cant do anything. the menu doesnt show when pressing home or to the button I change it to.
I cant do /command either.. 
I have to do addadmin ID everytime I log into the server too.

**Comment by Bluethefurry** [comment]
Are you getting any errors when you start EasyAdmin or you try to open a menu?

**Comment by Bluethefurry** [comment]
closed due to inactivity.
