### ISSUE TITLE
Slow query warning

### ISSUE THREAD

**Issue by ponduzn** [Bluethefurry/EasyAdmin#82]
Getting this warning:

"[MySQL] [Slow Query Warning] [EasyAdmin-MySQL] [53ms] SELECT count(*) FROM information_schema.COLUMNS WHERE COLUMN_NAME = 'discord' and TABLE_NAME = 'ea_bans'"

Anything you could\should improve, or am i a potato ? = )

**Comment by Bluethefurry** [comment]
this should only happen once if the resource starts and as such should cause no issues, also, issues like this are better suited for the EasyAdmin-MySQL Repository > https://github.com/Bluethefurry/EasyAdmin-MySQL/issues
