### ISSUE TITLE
Question: How to use screenshoot?

### ISSUE THREAD

**Issue by lvp11** [Bluethefurry/EasyAdmin#84]
Hey!

I need help using this convars:
setr ea_screenshoturl "https://wew.wtf/upload.php"
setr ea_screenshotfield "files[]"
There's any public upload server avaliable? How to use something like Imgur?
I've read the screenshot-basic but didn't get it..

Thanks!

(Sorry for my english, i'm brazilian).

**Comment by Bluethefurry** [comment]
if you don't understand the screenshot convars you can leave them empty, by default they swelect wew.wtf as upload service, if you don't want to use a seperate uploader you can ignore them.
