### ISSUE TITLE
On user join getting console error not checking ban

### ISSUE THREAD

**Issue by rgnix2** [Bluethefurry/EasyAdmin#89]
Error running system event handling function for resource EasyAdmin: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @EasyAdmin/admin_server.lua:679: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        @EasyAdmin/admin_server.lua:679: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

set ea_LanguageName "en"              
set ea_MenuButton "56"              
set ea_alwaysShowButtons "false"        
set ea_custombanlist "true"            
set ea_moderationNotification "https://discordapp.com/api/webhooks/"
set ea_minIdentifierMatches 1
set ea_enableDebugging "false"

Using mysql for ban list.

**Comment by rgnix2** [comment]
This all so prevents banning of users as it doesn't properly check the ban list cause it is getting the error above. If i find any other information ill report back

**Comment by Bluethefurry** [comment]
that means your https://github.com/Bluethefurry/EasyAdmin-MySQL is outdated.

**Comment by rgnix2** [comment]
Thats my mistake could have swore my fork was updated. Ill try that and report back.

**Comment by rgnix2** [comment]
Okay upgrading easyadmin-mysql resolved the issue mentioned above. However since you changed the db scheme it currently will break my automation i have around firewall blocking banned players. That issue is my end and ill need to rewrite that when i get some more time. Thanks for the response and help. I will close this out.
