### ISSUE TITLE
Error in console for EasyAdmin 4.9

### ISSUE THREAD

**Issue by ToLegit88** [Bluethefurry/EasyAdmin#90]
```
Error running system event handling function for resource EasyAdmin-4.9: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @EasyAdmin-4.9/admin_server.lua:679: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        @EasyAdmin-4.9/admin_server.lua:679: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
```

I have modified nothing on the source code

**Comment by Bluethefurry** [comment]
Please DM me your banlist file on discord: Blü#1410

**Comment by Bluethefurry** [comment]
seriously, stop reporting issues and then never checking back on them.

**Comment by ToLegit88** [comment]
Ok gut das ich das selber umprogrammiert habe das es geht.

**Comment by Bluethefurry** [comment]
Fuck you, honestly, instead of reporting what you fixed you go "nvm i fixed it by changing code!"

REPORT YOUR FUCKING ISSUES, CREATE PULL REQUESTS!

you guys are absolute fucking idiots, do you know that, i wish i could revoke access to easyadmin to some people, because you would be one of them.

**Comment by ToLegit88** [comment]
Toxic ;)

**Comment by Bluethefurry** [comment]
dont fucking call me toxic, im trying make a good fucking admin panel, people that keep their fixes to themselves are the scum of the earth, instead of keeping fixes to yourself how about reporting shit? actually no, keep it to yourself, you're banned from this repo.
