### ISSUE TITLE
Menu unable to be opened

### ISSUE THREAD

**Issue by GhostTurtle28** [Bluethefurry/EasyAdmin#91]
So when I press the hotkey button (I changed it to F7 since F2 is the same as lambda noclip) the menu dosent open but it makes a click sound as if your scrolling in a menu and nothing comes up. When I spam the menu nothing shows up but it still makes the clicking sound. Heres my server.cfg `#EasyAdmin
set ea_LanguageName "en"                # set our language to english
set ea_MenuButton "289"			# set our menu button to F2. default: "289"
set ea_alwaysShowButtons "false"	# we don't want to see buttons we can't even access, do we? default: "false"
set ea_moderationNotification "false"   # this can be either "false" or a discord webhook address, this will send a discord message if an admin takes actions against a player  ( such as banning and kicking )

#Admins
#Redrum

add_ace group.admin easyadmin allow	                 # allow all commands for admins

add_ace group.moderator easyadmin.kick allow		 # allow kicking
add_ace group.moderator easyadmin.spectate allow         # allow spectating
add_ace group.moderator easyadmin.freeze allow         # allow freezing
add_ace group.moderator easyadmin.ban allow		 # disallow banning
add_ace group.moderator easyadmin.unban allow		 # also disallow unbanning
add_ace group.moderator easyadmin.addadmin allow
add_ace group.moderator easyadmin.manageserver allow
add_ace group.moderator easyadmin.slap allow

add_principal identifier.steam:76561197986254841 group.moderator	# add a user to the moderator group, any identifier works this way.
add_principal identifier.steam:11000010C871511 group.admin`
Thanks in advance!

**Comment by Bluethefurry** [comment]
Any errors in your F8 logs? if it "clicks" but doesnt open that means somewhere in the chain NativeUI had a problem.

**Comment by rex2630** [comment]
yeah, same probme without any issues in the log. Only new versions do it

**Comment by GhostTurtle28** [comment]
I whent back and reinstalled it on my test server and im not getting any errors via console or F8. On the server bootup it shows that it loads properly with no errors. Sorry its been awhile since I posted just been busy lately.

**Comment by Bluethefurry** [comment]
which ersion are you using? make sure you are using an official release, i cant reproduce this.

**Comment by rex2630** [comment]
Im using official release (version 4.91) and menu opens only sometimes...

**Comment by Bluethefurry** [comment]
getting any errors? when is "sometimes", also, enable debugging ( check the configuration wiki page ) and send me the results when you join.

**Comment by rex2630** [comment]
No errors at all. U can try it yourself. It works only on random connect. If it doesnt work then most of the times reconnect will fix that

**Comment by Bluethefurry** [comment]
uh, no, i cant try it myself, because i cannot reproduce your issue, it works 100% reliably for me, like i said, any errors? use debugging and send me the logs in produces in the server console, also, what version?

**Comment by Bluethefurry** [comment]
Okay, from now on please join the support discord so we dont have a multiple day delay when troubleshooting,
https://discord.gg/UbsYrKx

**Comment by sharkbait246** [comment]
Do you guys know how to unban yourself in sketchful.io?
