### ISSUE TITLE
Error after updating with hotfix

### ISSUE THREAD

**Issue by MedicoreJelly** [Bluethefurry/EasyAdmin#93]
So I just recently updated EasyAdmin with the new hotfix and I'm getting an error that I didn't get before.
![image](https://user-images.githubusercontent.com/47407876/60197752-5309f080-9840-11e9-917d-569289786c44.png)

**Comment by Bluethefurry** [comment]
send me your banlist.json file on the FiveM Forums.

**Comment by Bluethefurry** [comment]
.. or not.
