### ISSUE TITLE
Version 4.91 - Players do not get auto-unbanned

### ISSUE THREAD

**Issue by jokel00** [Bluethefurry/EasyAdmin#94]
Hey Buddy!

I have a problem with this script...

The players on my server do not get auto-unbanned after some bans are expired. Do you know why that could be? I just installed the 4.91 Version and put my banlist.json file into the directory.

Thank you!

**Comment by Bluethefurry** [comment]
send me your banlist file on the FiveM Forums please.

**Comment by jokel00** [comment]
[banlist.txt](https://github.com/Bluethefurry/EasyAdmin/files/3365118/banlist.txt)

Don't wonder that it is a .txt file. I had to convert it because i can not upload .json files in here. But it is a json file.

**Comment by Bluethefurry** [comment]
Which ban specifically isnt expiring? the only non-permanent one i can see (Spielername: Lovell) expires tomorrow.

**Comment by jokel00** [comment]
In general every ban that is not perma. So such like 3 Weeks and stuff.

I suppose there is something wrong with the check if it is expired.

**Comment by Bluethefurry** [comment]
what happens if you add this:

```
{
    "reason":"test ban",
    "identifiers":["none"],
    "expire":1554650096
}
```

to your banlist? does that get deleted?

**Comment by jokel00** [comment]
I will try later, i will inform you! Thank you by the way for your time! :)

**Comment by jokel00** [comment]
So the manual entered value what you gave me got deleted. It doesn't appear in the banlist.json.

**Comment by Bluethefurry** [comment]
then your other bans will also get deleted, there is no issue here.

**Comment by jokel00** [comment]
Hmm okay, thank you buddy for your help and time ☺️
